---
abstract: 'the setting for mildew compiled for SMOP'
author:
  - 'Pawel Murias <pawelmurias@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mildew-Setting-SMOP
requires:
  Mildew: 0.05
  SMOP: 0.06
version: 0.03
